name: Build and Release Desktop App
on:
  workflow_dispatch:

jobs:
  build-desktop-app:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Build electron app
        run: |
          npm ci
          cat <<EOF > apps/web/.env
          INTERNAL_INTEGRATION_API_URL=${INTERNAL_INTEGRATION_API_URL}
          NEXT_PUBLIC_SVM_METRICS="https://fr64dzklc3.execute-api.us-west-2.amazonaws.com/prod"
          NEXT_PUBLIC_ADOBE_EMBED_API_KEY="a165f09589fc4cd29a574b37d1212a96"
          NEXT_PUBLIC_TARGET='electron'
          EOF
          npx turbo run build --filter web
          npx turbo run prepare-electron --filter web
          cd apps/desktop
          npm install -g @todesktop/cli@1.9.1
          todesktop build
        env:
          TODESKTOP_ACCESS_TOKEN: ${{ secrets.TODESKTOP_ACCESS_TOKEN }}
          TODESKTOP_EMAIL: ${{ secrets.TODESKTOP_EMAIL }}
          INTERNAL_INTEGRATION_API_URL: ${{ secrets.INTERNAL_INTEGRATION_API_URL }}
          NEXT_PUBLIC_SVM_METRICS: "https://fr64dzklc3.execute-api.us-west-2.amazonaws.com/prod"
          NEXT_PUBLIC_ADOBE_EMBED_API_KEY: "a165f09589fc4cd29a574b37d1212a96"
          NEXT_PUBLIC_TARGET: "electron"
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

  test-desktop-app:
    runs-on: ubuntu-latest
    needs: build-desktop-app
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Smoke test electron app
        run: |
          npm install -g @todesktop/cli@1.9.1
          cd apps/desktop
          todesktop smoke-test
        env:
          TODESKTOP_ACCESS_TOKEN: ${{ secrets.TODESKTOP_ACCESS_TOKEN }}
          TODESKTOP_EMAIL: ${{ secrets.TODESKTOP_EMAIL }}

  release-desktop-app:
    needs: test-desktop-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Smoke test electron app
        run: |
          npm install -g @todesktop/cli@1.9.1
          cd apps/desktop
          todesktop release --latest
        env:
          TODESKTOP_ACCESS_TOKEN: ${{ secrets.TODESKTOP_ACCESS_TOKEN }}
          TODESKTOP_EMAIL: ${{ secrets.TODESKTOP_EMAIL }}
